##
# @file
#
# Travis script for queue
#
# @author Tim Ewart
#

dist: trusty
sudo: false
language: cpp
compiler:
  - gcc
  - clang
addons:
  apt:
    packages:
    - clang
    - libboost-all-dev
    - cmake
before_script:
  - mkdir build
  - cd build
  - cmake -DQUEUE_TESTS=on ..
script:
  - make
  - make test
notifications:
  email:
    recipients:
      - timothee.ewart@gmail.com
    on_success: change
    on_failure: always

