##
# @file
#
# Travis script for queue
#
# @author Tim Ewart
#

sudo: required
dist: trusty
language: cpp
compiler:
  - gcc
  - clang
addons:
  apt:
    packages:
    - libboost-all-dev
    - libtbb-dev
before_script:
  - mkdir build
  - cd build
  - cmake -DQUEUE_TESTS=on ..
script:
  - make
  - ctest
notifications:
  email:
    recipients:
      - timothee.ewart@gmail.com
    on_success: change
    on_failure: always

